routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){

    Route::get('divisions/ajax_update', 'DivisionController@ajax_update')->middleware('roles:admin');

    Route::resource('divisions', 'DivisionController')->middleware('roles:admin');

    Route::get('districts/ajax_update', 'DistrictController@ajax_update')->middleware('roles:admin,division');

    Route::resource('districts', 'DistrictController')->middleware('roles:admin,division');
    
    Route::resource('users', 'UserController')->middleware('roles:admin,division,district');   
    
});

app/District.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class District extends Model
{
    protected $fillable = ['name', 'division_id'];

    public function division(){
        return $this->belongsTo(\App\Division::class);
    }
}

app/Http/Controllers/DistrictController.php
<?php

namespace App\Http\Controllers;

use App\District;
use App\Division;
use Illuminate\Http\Request;
use App\Http\Requests\DistrictStoreRequest;
use App\Http\Requests\DistrictUpdateRequest;
use Illuminate\Database\QueryException;
use TheSeer\Tokenizer\Exception;

class DistrictController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $districts = $this->allowed_districts()->paginate(10);


        return \view('districts.index', compact('districts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $divisions = Division::pluck('name', 'id');
        return \view('districts.create', compact('divisions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DistrictStoreRequest $request)
    {
        $districts = $request->store();

        if($districts){
            return redirect('districts')->with('message', 'District Saved!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function show(District $district)
    {
        \in_array($district->id, $this->allowed_districts()->pluck('id')->toArray()) ? '':abort(403);
        return \view('districts.show', compact('district'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function edit(District $district)
    {
        \in_array($district->id, $this->allowed_districts()->pluck('id')->toArray()) ? '':abort(403);
        return \view('districts.edit', compact('district'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function update(DistrictUpdateRequest $request, District $district)
    {
        $districts = $request->update($district);

        if($districts){
            return redirect('districts')->with('message', 'District Updated!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\District  $district
     * @return \Illuminate\Http\Response
     */
    public function destroy(District $district)
    {
        try{
            District::findOrFail($district->id)->delete();
        }catch(QueryException $error){
            return $error->errorInfo;
        }catch(Exception $exception){
            return $exception->getCode();
        }

        return redirect()->back()->with('message', 'District deleted!');
    }

    private function allowed_districts(){
        $districts = District::with('division')
        ->when(auth()->user()->user_role->role_id != 1, function($district){
            $district->when(auth()->user()->user_attached_district == null, function($district){
                    $district->whereHas('division', function($division){
                            $division->where('id', optional(auth()->user()->user_attached_division)->division_id);
                        });
                })
                ->orWhere('id', optional(auth()->user()->user_attached_district)->district_id)
                ;
        })
        ->orderByDesc('id');

        return $districts;
    }

    public function ajax_update(Request $request){

        if($request->ajax()){
            $district = District::findOrFail($request->id)->update([
                'name' => $request->name
            ]);
    
            if($district){
                return true;
            }
        }

    }

}

resources/views/districts/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Districts Create') }}</div>

                <div class="card-body">
                    @if($errors->any())
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif

                    <form action="{{ route('districts.store') }}" method="post">
                        @csrf
                       
                        <div class="form-group">
                            <label>Division</label>
                            <select name="division_id" class="form-control">
                                @foreach($divisions as $id => $name)     
                                    <option value="{{ $id }}">{{ $name }}</option>
                                @endforeach
                            </select>
                        </div>
                       
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" value="">
                        </div>
                        
                        <div class="form-group">
                            <input type="submit" value="Save" type="submit" class="btn btn-primary">
                        </div>            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/districts/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Districts Edit') }}</div>

                <div class="card-body">
                    @if($errors->any())
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif

                    <form action="{{ route('districts.update', $district->id) }}" method="post">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{ $district->id }}">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $district->name }}">
                        </div>
                        
                        <div class="form-group">
                            <input type="submit" value="Save" type="submit" class="btn btn-primary">
                        </div>            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/districts/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Districts') }}</div>

                <div class="card-body">
                    
                    @if(Session::get('message'))
                    <div class="alert alert-success">
                            {{ Session::get('message') }}
                    </div>
                    @endif

                    <table class="table" id="districtTable">
                            <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Division</th>
                                        <th>Action</th>    
                                    </tr>   
                                </thead>
        
                                @forelse($districts as $district)
                                <tbody>
                                    <tr>
                                        <td>
                                            <input type="text" class="no-border-input" value="{{ $district->name }}" onblur="updateDistrict(this.value, {{ $district->id }})">
                                        </td>
                                        <td>{{ $district->division->name }}</td>
                                        <td>
                                            <ul class="list-unstyled list-inline">
                                                <li class="list-inline-item">
                                                    <a href="{{ route('districts.show', $district->id) }}" class="btn btn-sm btn-primary">View</a>
                                                </li>
        
                                                <li class="list-inline-item">
                                                    <a href="{{ route('districts.edit', $district->id) }}" class="btn btn-sm btn-success">Edit</a>
                                                </li>
        
                                                <li class="list-inline-item">
                                                    <a href="#" class="btn btn-sm btn-danger" onclick="formSubmit('{{ $district->id }}')">Delete</a>
        
                                                    <form action="{{route('districts.destroy', $district->id)}}" id="deleteForm_{{$district->id}}" method="POST">
                                                        @csrf
                                                        @method("DELETE")
                                                    </form>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                </tbody>
        
                                @empty
                                    <tr>
                                        <td>
                                            No data found!
                                        </td>
                                    </tr>
                                @endforelse
                    </table>  

                    {{ $districts->links() }}
                </div>
            </div>
        </div>
    </div>
</div>



<!-- Data table plugin-->
<script type="text/javascript" src="{{ asset('assets/js/plugins/sweetalert.min.js')}}"></script>




<script>

    
    function formSubmit(id)
        {
            
          swal({
            title: "Are you sure?",
            text: "You will not be able to recover this data !",
            type: "warning",
            showCancelButton: true,
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plz!",
            closeOnConfirm: false,
            closeOnCancel: false
          }, function(isConfirm) {
            if (isConfirm) {
              $('#deleteForm_'+id).submit();
              swal("Deleted!", "Your data has been deleted.", "success");
            } else {
              swal("Cancelled", "Your data is safe :)", "error");
            }
          });
        }



function updateDistrict(name, id){
    $.ajax({
        url: 'districts/ajax_update?name='+name+'&id='+id,
        type: 'GET',
        success: function(){
            alert('District updated!');
        }
    });
}
</script>
@endsection

resources/views/districts/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('District Show') }}</div>

                <div class="card-body">
                    
                        <table class="table table-condensed">
                                <tr>
                                    <th>District Name</th>
                                    <td>{{ $district->name }}</td>        
                                </tr>
                                <tr>
                                    <th>Division</th>
                                    <td>{{ $district->division->name ?? '' }}</td>
                                </tr>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection