routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){

    Route::get('divisions/ajax_update', 'DivisionController@ajax_update')->middleware('roles:admin');

    Route::resource('divisions', 'DivisionController')->middleware('roles:admin');

    Route::get('districts/ajax_update', 'DistrictController@ajax_update')->middleware('roles:admin,division');

    Route::resource('districts', 'DistrictController')->middleware('roles:admin,division');
    
    Route::resource('users', 'UserController')->middleware('roles:admin,division,district');   
    
});

app/Division.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Division extends Model
{
    protected $fillable = ['name'];

    public function district(){
        return $this->hasMany(District::class);
    }
}

app/Http/Controllers/DivisionController.php
<?php

namespace App\Http\Controllers;

use App\Division;
use Illuminate\Http\Request;
use App\Http\Requests\DivisionStoreRequest;
use App\Http\Requests\DivisionUpdateRequest;
use PHPUnit\Framework\Exception;
use Illuminate\Database\QueryException;

class DivisionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $divisions = Division::orderByDesc('id')->get();
        return \view('divisions.index', compact('divisions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return \view('divisions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DivisionStoreRequest $request)
    {
        
        $divisions = $request->store();

        if($divisions){
            return redirect('divisions')->with('message', 'Division saved!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function show(Division $division)
    {
        return \view('divisions.show', compact('division'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function edit(Division $division)
    {
        return \view('divisions.edit', compact('division'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function update(DivisionUpdateRequest $request, Division $division)
    {
        $divisions = $request->update($division);

        if($divisions){
            return redirect('divisions')->with('message', 'Division updated!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Division  $division
     * @return \Illuminate\Http\Response
     */
    public function destroy(Division $division)
    {
        try{
            Division::destroy($division->id);
        }
        catch(QueryException $error){
            return $error->errorInfo;   
        }catch(Exception $exception){
            return $exception->getCode().' You cano not delete this division';
        }

        return \redirect()->back()->with('message', 'Division deleted!');
    }

    public function ajax_update(Request $request){

        if($request->ajax()){
            $division = Division::findOrFail($request->id)->update([
                'name' => $request->name
            ]);
    
            if($division){
                return true;
            }
        }

    }

}

resources/views/divisions/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Division Create') }}</div>

                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">

                            @if($errors->any())
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            @endif

                            <form action="{{ route('divisions.store') }}" method="post">
                                @csrf
                                <div class="form-group">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="name" value="">
                                </div>
                                
                                <div class="form-group">
                                    <input type="submit" value="Save" type="submit" class="btn btn-primary">
                                </div>            
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/divisions/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Division Edit') }}</div>

                <div class="card-body">
                    @if($errors->any())
                        <ul>
                            @foreach($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    @endif

                    <form action="{{ route('divisions.update', $division->id) }}" method="post">
                        @csrf
                        @method('put')
                        <input type="hidden" name="id" value="{{ $division->id }}">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control" name="name" value="{{ $division->name }}">
                        </div>
                        
                        <div class="form-group">
                            <input type="submit" value="Save" type="submit" class="btn btn-primary">
                        </div>            
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/divisions/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Division List') }}</div>

                <div class="card-body">
                    
                    @if(Session::get('message'))
                    <div class="alert alert-success">
                        {{ Session::get('message') }}
                    </div>
                    @endif
                    
                    <table class="table" id="divisionTable">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Action</th>    
                            </tr>   
                        </thead>

                        @forelse($divisions as $division)
                        <tbody>
                            <tr>
                                <td>
                                    <input type="text" class="no-border-input" value="{{ $division->name }}" onblur="updateDivision(this.value, {{ $division->id }})">
                                </td>
                                <td>
                                    <ul class="list-unstyled list-inline">
                                        <li class="list-inline-item">
                                            <a href="{{ route('divisions.show', $division->id) }}" class="btn btn-sm btn-primary">View</a>
                                        </li>

                                        <li class="list-inline-item">
                                            <a href="{{ route('divisions.edit', $division->id) }}" class="btn btn-sm btn-success">Edit</a>
                                        </li>

                                        <li class="list-inline-item">
                                            <a href="#" class="btn btn-sm btn-danger" onclick="formSubmit('{{ $division->id }}')">Delete</a>

                                            <form action="{{route('divisions.destroy', $division->id)}}" id="deleteForm_{{$division->id}}" method="POST">
                                                @csrf
                                                @method("DELETE")
                                            </form>
                                        </li>
                                    </ul>
                                </td>
                            </tr>
                        </tbody>

                        @empty
                            <tr>
                                <td>
                                    No data found!
                                </td>
                            </tr>
                        @endforelse
                    </table>  
                </div>
            </div>
        </div>
    </div>
</div>

{{-- <script src="{{ asset('assets/js/jquery-3.2.1.min.js') }}"></script> --}}
<!-- Data table plugin-->
<script type="text/javascript" src="{{ asset('assets/js/plugins/jquery.dataTables.min.js')}}"></script>
<script type="text/javascript" src="{{ asset('assets/js/plugins/dataTables.bootstrap.min.js')}}"></script>
 
<script type="text/javascript" src="{{ asset('assets/js/plugins/sweetalert.min.js')}}"></script>


<script type="text/javascript">$('#divisionTable').DataTable();</script>


<script>

    
    function formSubmit(id)
        {
            
          swal({
            title: "Are you sure?",
            text: "You will not be able to recover this data !",
            type: "warning",
            showCancelButton: true,
            confirmButtonText: "Yes, delete it!",
            cancelButtonText: "No, cancel plz!",
            closeOnConfirm: false,
            closeOnCancel: false
          }, function(isConfirm) {
            if (isConfirm) {
              $('#deleteForm_'+id).submit();
              swal("Deleted!", "Your data has been deleted.", "success");
            } else {
              swal("Cancelled", "Your data is safe :)", "error");
            }
          });
        }



function updateDivision(name, id){
    $.ajax({
        url: 'divisions/ajax_update?name='+name+'&id='+id,
        type: 'GET',
        success: function(){
            alert('Division updated!');
        }
    });
}
</script>




@endsection

resources/views/divisions/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Division Show') }}</div>

                <div class="card-body">
                        <table class="table table-bordered">
                            <tr>
                                <th>Name</th>
                                <td>{{ $division->name }}</td>        
                            </tr>
                        </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection